system:
    default:
        yui:
            modules:
                showdown:
                    path: %ez_platformui.fieldtype.markdown.public_dir%/js/vendors/showdown/showdown.js
                md-showdown:
                    requires: ['showdown']
                    path: %ez_platformui.fieldtype.markdown.public_dir%/js/external/md-showdown.js
                md-markdown-view:
                    requires:
                        - 'ez-fieldview'
                        - 'ez-translator'
                        - 'md-showdown'
                        - 'mdmarkdownview-ez-template'
                    dependencyOf: ['ez-rawcontentview']
                    path: %ez_platformui.fieldtype.markdown.public_dir%/js/views/fields/md-markdown-view.js
                mdmarkdownview-ez-template:
                    type: 'template'
                    path: %ez_platformui.fieldtype.markdown.public_dir%/templates/fields/view/markdown.hbt
                md-markdown-editview:
                    requires:
                        - 'ez-fieldeditview'
                        - 'ez-translator'
                        - 'md-showdown'
                        - 'event-valuechange'
                        - 'mdmarkdowneditview-ez-template'
                    dependencyOf: ['ez-contenteditformview']
                    path: %ez_platformui.fieldtype.markdown.public_dir%/js/views/fields/md-markdown-editview.js
                mdmarkdowneditview-ez-template:
                    type: 'template'
                    path: %ez_platformui.fieldtype.markdown.public_dir%/templates/fields/edit/markdown.hbt
